#!/usr/local/bin/php -q
<?php
include __DIR__ . '/config/config.inc.php';

$root_pass = getenv("DB_ROOT_PASS");
if ($root_pass) {
    $prefix = $argv[1] ?? "RC_";
    $db = getenv("${prefix}DB_NAME");

    $conn = new mysqli(getenv("${prefix}DB_HOST"), "root", $root_pass);

    if ($conn->connect_error) {
        print("Connection failed: " . $conn->connect_error);
        exit(1);
    }

    $res = $conn->query("CREATE DATABASE IF NOT EXISTS " . $db)
        && $conn->query("GRANT ALL PRIVILEGES ON `${db}`.* TO '" . getenv("${prefix}DB_USER") ."'@'%' WITH GRANT OPTION")
        && $conn->query("FLUSH PRIVILEGES");

    $conn->close();

    if (!$res) {
        print("DB error: " . $conn->error);
        exit(1);
    }

}